### ISSUE TITLE
There is error message on use btrace on Apache Tomcat/7.0.39

### ISSUE THREAD

**Issue by Jared12** [jbachorik/btrace#105]
here are error message as below:

  
HTTP Status 500 - org.glassfish.jersey.server.ContainerException: java.lang.VerifyError: Bad type on operand stack
 
type Exception report
message org.glassfish.jersey.server.ContainerException: java.lang.VerifyError: Bad type on operand stack
description The server encountered an internal error that prevented it from fulfilling this request.
exception
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/starcite/glcnew/rfp/util/ResponsePaladin.buildBasicData(Ljava/lang/String;)V @453: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[4]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @453
    flags: { }
    locals: { 'com/starcite/glcnew/rfp/util/ResponsePaladin', 'java/lang/String', long, long_2nd, 'java/lang/Object' }
    stack: { uninitialized 441, uninitialized 441, 'java/lang/String', 'java/lang/String', 'java/lang/Object' }
  Bytecode:
    0000000: b800 5d41 2abb 008b 59b7 008c b500 7f2a
    0000010: 2ab4 006b 2b2a b400 6fb9 0092 0300 b500
    0000020: 942a bb00 9659 b700 97b5 0099 2ab4 0099
    0000030: 2ab4 0094 b600 9fb6 00a2 2ab4 0099 2ab4
    0000040: 0094 b600 a5b6 00a8 2ab4 0099 2ab4 0094
    0000050: b600 abb6 00ae 2ab4 0099 2ab4 0094 b600
    0000060: b1b6 00b4 2ab4 0099 2ab4 0094 b600 b7b6
    0000070: 00ba 2ab4 0099 2ab4 0094 b600 bdb6 00c0
    0000080: 2ab4 0099 2ab4 0094 b600 c3b6 00c6 2ab4
    0000090: 0099 2ab4 0094 b600 c9b6 00cc 2ab4 0099
    00000a0: 2ab4 0094 b600 d0c6 0010 2ab4 0094 b600
    00000b0: d0b6 00d6 a700 0401 b600 da2a b400 94b6
    00000c0: 00de 3a04 1904 c600 6f19 04be 9e00 69bb
    00000d0: 00e0 5919 04be b700 e33a 0519 043a 0619
    00000e0: 06be 3607 0336 0815 0815 07a2 0041 1906
    00000f0: 1508 323a 09bb 00e5 59b7 00e6 3a0a 190a
    0000100: 1909 b600 ebb6 00ee 190a 1909 b600 f1b6
    0000110: 00f4 190a 1909 b600 f7b6 00fa 1905 190a
    0000120: b901 0002 0057 8408 01a7 ffbe 2ab4 007f
    0000130: 1905 b601 0419 04c6 007d 1904 be9e 0077
    0000140: bb00 e059 1904 beb7 00e3 3a05 1904 3a06
    0000150: 1906 be36 0703 3608 1508 1507 a200 4f19
    0000160: 0615 0832 3a09 bb01 0659 b701 073a 0a19
    0000170: 0a13 0109 b601 0abb 010c 59b7 010d 3a0b
    0000180: 190b 1909 b600 f1b6 0110 190b 1909 b600
    0000190: ebb6 0113 190a 190b b601 1719 0519 0ab9
    00001a0: 0100 0200 5784 0801 a7ff b02a b400 7f19
    00001b0: 05b6 011a a700 153a 04bb 011c 5913 011e
    00001c0: 1301 2019 04b7 0123 bfb8 005d 370c 1301
    00001d0: 2516 0c20 65b8 0075 1301 2516 0c20 65b8
    00001e0: 0078 b1                                
  Exception Handler Table:
    bci [4, 436] => handler: 439
    bci [4, 436] => handler: 439
    bci [4, 436] => handler: 439
  Stackmap Table:
    full_frame(@183,{Object[#2],Object[#317],Long},{Object[#150]})
    full_frame(@184,{Object[#2],Object[#317],Long},{Object[#150],Object[#319]})
    full_frame(@231,{Object[#2],Object[#317],Long,Object[#320],Object[#224],Object[#320],Integer,Integer},{})
    same_frame_extended(@300)
    full_frame(@309,{Object[#2],Object[#317],Long,Object[#320]},{})
    full_frame(@344,{Object[#2],Object[#317],Long,Object[#320],Object[#224],Object[#320],Integer,Integer},{})
    same_frame_extended(@427)
    full_frame(@436,{Object[#2],Object[#317],Long,Object[#320]},{})
    full_frame(@439,{Object[#2],Object[#317],Long},{Object[#4]})
    append_frame(@457,Object[#320])

	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:393)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	com.starcite.glcnew.security.impl.SecurityFilter.doFilter(SecurityFilter.java:26)
	ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:51)
	com.starcite.glcnew.filter.MDCLogFilter.doFilter(MDCLogFilter.java:40)
root cause
org.glassfish.jersey.server.ContainerException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/starcite/glcnew/rfp/util/ResponsePaladin.buildBasicData(Ljava/lang/String;)V @453: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[4]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @453
    flags: { }
    locals: { 'com/starcite/glcnew/rfp/util/ResponsePaladin', 'java/lang/String', long, long_2nd, 'java/lang/Object' }
    stack: { uninitialized 441, uninitialized 441, 'java/lang/String', 'java/lang/String', 'java/lang/Object' }
  Bytecode:
    0000000: b800 5d41 2abb 008b 59b7 008c b500 7f2a
    0000010: 2ab4 006b 2b2a b400 6fb9 0092 0300 b500
    0000020: 942a bb00 9659 b700 97b5 0099 2ab4 0099
    0000030: 2ab4 0094 b600 9fb6 00a2 2ab4 0099 2ab4
    0000040: 0094 b600 a5b6 00a8 2ab4 0099 2ab4 0094
    0000050: b600 abb6 00ae 2ab4 0099 2ab4 0094 b600
    0000060: b1b6 00b4 2ab4 0099 2ab4 0094 b600 b7b6
    0000070: 00ba 2ab4 0099 2ab4 0094 b600 bdb6 00c0
    0000080: 2ab4 0099 2ab4 0094 b600 c3b6 00c6 2ab4
    0000090: 0099 2ab4 0094 b600 c9b6 00cc 2ab4 0099
    00000a0: 2ab4 0094 b600 d0c6 0010 2ab4 0094 b600
    00000b0: d0b6 00d6 a700 0401 b600 da2a b400 94b6
    00000c0: 00de 3a04 1904 c600 6f19 04be 9e00 69bb
    00000d0: 00e0 5919 04be b700 e33a 0519 043a 0619
    00000e0: 06be 3607 0336 0815 0815 07a2 0041 1906
    00000f0: 1508 323a 09bb 00e5 59b7 00e6 3a0a 190a
    0000100: 1909 b600 ebb6 00ee 190a 1909 b600 f1b6
    0000110: 00f4 190a 1909 b600 f7b6 00fa 1905 190a
    0000120: b901 0002 0057 8408 01a7 ffbe 2ab4 007f
    0000130: 1905 b601 0419 04c6 007d 1904 be9e 0077
    0000140: bb00 e059 1904 beb7 00e3 3a05 1904 3a06
    0000150: 1906 be36 0703 3608 1508 1507 a200 4f19
    0000160: 0615 0832 3a09 bb01 0659 b701 073a 0a19
    0000170: 0a13 0109 b601 0abb 010c 59b7 010d 3a0b
    0000180: 190b 1909 b600 f1b6 0110 190b 1909 b600
    0000190: ebb6 0113 190a 190b b601 1719 0519 0ab9
    00001a0: 0100 0200 5784 0801 a7ff b02a b400 7f19
    00001b0: 05b6 011a a700 153a 04bb 011c 5913 011e
    00001c0: 1301 2019 04b7 0123 bfb8 005d 370c 1301
    00001d0: 2516 0c20 65b8 0075 1301 2516 0c20 65b8
    00001e0: 0078 b1                                
  Exception Handler Table:
    bci [4, 436] => handler: 439
    bci [4, 436] => handler: 439
    bci [4, 436] => handler: 439
  Stackmap Table:
    full_frame(@183,{Object[#2],Object[#317],Long},{Object[#150]})
    full_frame(@184,{Object[#2],Object[#317],Long},{Object[#150],Object[#319]})
    full_frame(@231,{Object[#2],Object[#317],Long,Object[#320],Object[#224],Object[#320],Integer,Integer},{})
    same_frame_extended(@300)
    full_frame(@309,{Object[#2],Object[#317],Long,Object[#320]},{})
    full_frame(@344,{Object[#2],Object[#317],Long,Object[#320],Object[#224],Object[#320],Integer,Integer},{})
    same_frame_extended(@427)
    full_frame(@436,{Object[#2],Object[#317],Long,Object[#320]},{})
    full_frame(@439,{Object[#2],Object[#317],Long},{Object[#4]})
    append_frame(@457,Object[#320])

	org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:256)
	org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:238)
	org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:439)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	com.starcite.glcnew.security.impl.SecurityFilter.doFilter(SecurityFilter.java:26)
	ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:51)
	com.starcite.glcnew.filter.MDCLogFilter.doFilter(MDCLogFilter.java:40)
root cause
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/starcite/glcnew/rfp/util/ResponsePaladin.buildBasicData(Ljava/lang/String;)V @453: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[4]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @453
    flags: { }
    locals: { 'com/starcite/glcnew/rfp/util/ResponsePaladin', 'java/lang/String', long, long_2nd, 'java/lang/Object' }
    stack: { uninitialized 441, uninitialized 441, 'java/lang/String', 'java/lang/String', 'java/lang/Object' }
  Bytecode:
    0000000: b800 5d41 2abb 008b 59b7 008c b500 7f2a
    0000010: 2ab4 006b 2b2a b400 6fb9 0092 0300 b500
    0000020: 942a bb00 9659 b700 97b5 0099 2ab4 0099
    0000030: 2ab4 0094 b600 9fb6 00a2 2ab4 0099 2ab4
    0000040: 0094 b600 a5b6 00a8 2ab4 0099 2ab4 0094
    0000050: b600 abb6 00ae 2ab4 0099 2ab4 0094 b600
    0000060: b1b6 00b4 2ab4 0099 2ab4 0094 b600 b7b6
    0000070: 00ba 2ab4 0099 2ab4 0094 b600 bdb6 00c0
    0000080: 2ab4 0099 2ab4 0094 b600 c3b6 00c6 2ab4
    0000090: 0099 2ab4 0094 b600 c9b6 00cc 2ab4 0099
    00000a0: 2ab4 0094 b600 d0c6 0010 2ab4 0094 b600
    00000b0: d0b6 00d6 a700 0401 b600 da2a b400 94b6
    00000c0: 00de 3a04 1904 c600 6f19 04be 9e00 69bb
    00000d0: 00e0 5919 04be b700 e33a 0519 043a 0619
    00000e0: 06be 3607 0336 0815 0815 07a2 0041 1906
    00000f0: 1508 323a 09bb 00e5 59b7 00e6 3a0a 190a
    0000100: 1909 b600 ebb6 00ee 190a 1909 b600 f1b6
    0000110: 00f4 190a 1909 b600 f7b6 00fa 1905 190a
    0000120: b901 0002 0057 8408 01a7 ffbe 2ab4 007f
    0000130: 1905 b601 0419 04c6 007d 1904 be9e 0077
    0000140: bb00 e059 1904 beb7 00e3 3a05 1904 3a06
    0000150: 1906 be36 0703 3608 1508 1507 a200 4f19
    0000160: 0615 0832 3a09 bb01 0659 b701 073a 0a19
    0000170: 0a13 0109 b601 0abb 010c 59b7 010d 3a0b
    0000180: 190b 1909 b600 f1b6 0110 190b 1909 b600
    0000190: ebb6 0113 190a 190b b601 1719 0519 0ab9
    00001a0: 0100 0200 5784 0801 a7ff b02a b400 7f19
    00001b0: 05b6 011a a700 153a 04bb 011c 5913 011e
    00001c0: 1301 2019 04b7 0123 bfb8 005d 370c 1301
    00001d0: 2516 0c20 65b8 0075 1301 2516 0c20 65b8
    00001e0: 0078 b1                                
  Exception Handler Table:
    bci [4, 436] => handler: 439
    bci [4, 436] => handler: 439
    bci [4, 436] => handler: 439
  Stackmap Table:
    full_frame(@183,{Object[#2],Object[#317],Long},{Object[#150]})
    full_frame(@184,{Object[#2],Object[#317],Long},{Object[#150],Object[#319]})
    full_frame(@231,{Object[#2],Object[#317],Long,Object[#320],Object[#224],Object[#320],Integer,Integer},{})
    same_frame_extended(@300)
    full_frame(@309,{Object[#2],Object[#317],Long,Object[#320]},{})
    full_frame(@344,{Object[#2],Object[#317],Long,Object[#320],Object[#224],Object[#320],Integer,Integer},{})
    same_frame_extended(@427)
    full_frame(@436,{Object[#2],Object[#317],Long,Object[#320]},{})
    full_frame(@439,{Object[#2],Object[#317],Long},{Object[#4]})
    append_frame(@457,Object[#320])

	com.starcite.glcnew.service.integration.impl.ResponseServiceImpl.getResponseBean(ResponseServiceImpl.java:513)
	com.starcite.glcnew.service.integration.impl.ResponseServiceImpl.getResponseForView(ResponseServiceImpl.java:596)
	com.starcite.glcnew.resources.ResponseResource.viewResponse(ResponseResource.java:273)
	sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	com.starcite.glcnew.security.impl.SecurityFilter.doFilter(SecurityFilter.java:26)
	ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:51)
	com.starcite.glcnew.filter.MDCLogFilter.doFilter(MDCLogFilter.java:40)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.39 logs.
 
Apache Tomcat/7.0.39

**Comment by jbachorik** [comment]
Long time no response. Closing.
If still applicable, feel free to reopen.
