### ISSUE TITLE
The offset of sizeof method in com.sun.btrace.BTraceUtils class is large

### ISSUE THREAD

**Issue by tdy218** [jbachorik/btrace#122]
I'm using to calculate the attribute size which put into a httpsession, and then i found the sizeof method in com.sun.btrace.BTraceUtils class  had  certain error.

My webapp main dode
<pre><code>String[] aArray = new String[4096];
session.setAttribute("session_pass",session.getId());
</code></pre>

BTrace Script main code
<pre><code>@OnMethod(
	clazz = "weblogic.servlet.internal.session.SessionData",
	method = "setAttribute",
	type = "void (java.lang.String, java.lang.Object, boolean) throws"
)	
public static void OnSetAttribute(@Self Object obj, @ProbeMethodName String pmn, AnyType[] args){
	println(strcat(strcat(timestamp("yyyy-MM-dd HH:mm:ss"), " -> "), "Session size changed."));
	println(strcat("Set Attribute Name : ", str(args[0])));
	println(strcat(strcat(strcat(strcat("Set Attribute Value : ", str(args[1])), ", and Attribute Size is "), str(sizeof(args[1]))), " bytes."));
	jstack();
}
</code></pre>

and then i got the following output

>2015-05-19 10:29:14 -> Session size changed.</br>
Set Attribute Name : session_pass</br>
Set Attribute Value : [Ljava.lang.String;@5b6ef20, and Attribute Size is 16400 bytes.</br>

The WebLogic Server's httpsession attribute size output
><[HTTP Session:100077]HTTPSession attribute: "session_pass" is of size 4,140 bytes.>

**Comment by tdy218** [comment]
BTW, the btrace's version is 1.2.5.1

**Comment by marschall** [comment]
After a quick back of the envelope calculation I can explain the BTrace values but not the WebLogic values. The BTrace values seem correct.
Size of a `String[4096]`:
<dl>
<dt>4096 * 32bit (4 bytes)<dt>
<dd>for the actual elements/oops (on a 32bit VM or 64bit VM with compressed oops)<dd>
<dt>32bit (4 bytes)</dt><dd>for the array length</dd>
<dt>2 * 32bit (4 bytes)</dt><dd>for the object header (on HotSpot 32bit VM or 64bit VM with compressed oops)<dd>
<dt>4 byte</dt><dd>padding to next multiple of 64bit (4 bytes)</dd>
<dl>

It may be that WebLogic stores by value (eg. serialization) and applies some compression.

**Comment by jbachorik** [comment]
The `sizeof` method is using the value reported by JVM.
As @marschall analysis points out the WLS value might be affected by internal optimizations.
