### ISSUE TITLE
Unable to open socket file: target process not responding or HotSpot VM not loaded

### ISSUE THREAD

**Issue by DerekYangYC** [jbachorik/btrace#139]
The start script: 

```bash
export JAVA_HOME=/home/abc/jdk-1.7.0_45
export PATH=$JAVA_HOME:$PATH
/home/abc/btrace/bin/btrace 26515 /home/abc/btrace/samples/SocketTracker.java
```

And the output:
```bash
-bash-3.2$ ./start-btrace.sh
Unable to open socket file: target process not responding or HotSpot VM not loaded
```

The application I am running is Tomcat web app with customized temp folder

**Comment by jbachorik** [comment]
The __btrace__ command has the following form:
`btrace <args> <PID> <script path>`

In your start script you are using __26515__ for __PID__. The message you see indicates that this PID corresponds to a non-JVM process. You should use the actual PID of the JVM process you want BTrace to attach to.

Closing for now. If you are sure you are providing a correct PID, please reopen.

**Comment by DerekYangYC** [comment]
I'm sure I found a correct **PID**(After reboot, it's now **2898** instead of **26515**). My web application is hosted in `Tomcat-7.0.30` with `jdk-1.6.0_24` (yes, I know it' old and should be deprecated) and customized temp folder. Here is the output:

```bash
-bash-3.2$ /home/sunjava-1.6.0_24/bin/jps -J-Djava.io.tmpdir=/home/temp
2898 Bootstrap
17644 Jps
-bash-3.2$ export JAVA_HOME=/home/abc/jdk-1.7.0_45
-bash-3.2$ export PATH=$JAVA_HOME:$PATH
-bash-3.2$ /home/abc/btrace/bin/btrace 2898 /home/abc/btrace/samples/SocketTracker.java
Unable to open socket file: target process not responding or HotSpot VM not loaded
-bash-3.2$
```

I'm not sure if it's a issue with jdk6. But `Btrace` couldn't connect to my application.

**Comment by jbachorik** [comment]
If you are using __BTrace 1.3.*__  this is definitely issue with JDK 6. BTrace classes are compiled to the newer, JDK 7, format and JDK 7 can't load them. Therefore the the attempt to attach to Tomcat fails.

I really hate repeating it but - JDK 6 is a prehistoric, non-supported runtime. A number of issues was fixed and enhancements made for BTrace to work more reliably. Given that JDK 7 has already been EOL-ed I think it might be considered to be mature enough platform.

**Comment by jbachorik** [comment]
Unsupported scenario. Closing.

**Comment by uninxc** [comment]
check the user is same one!

**Comment by majintao** [comment]
@uninxc  You are right!
