### ISSUE TITLE
Hanging at checking port availability: 2020

### ISSUE THREAD

**Issue by Proofkyko** [jbachorik/btrace#141]
Hello, I am a newcomer to btrace and right now I can not even run the samples as btrace simply hangs at :
DEBUG: checking port availability: 2020
Do you know any bug that could be related ? I searched and no processing is using that port.
Hope you can help

**Comment by jbachorik** [comment]
Could you specify OS and JDK version you are using?

**Comment by Proofkyko** [comment]
I am working on windows 7, Java version 1.7.0_60. Hope you can help !

No dia 24/07/2015, às 16:22, Jaroslav Bachorik <notifications@github.com> escreveu:

**Comment by jbachorik** [comment]
I am not able to reproduce the issue on the given OS and JDK.

After the message 'DEBUG: checking port availability: 2020' has been printed the agent tries to connect to IP 127.0.0.1 on port 2020 to make sure that it is available. Could this be blocked by your firewall, perhaps?

You could try and take stack traces of the traced application when this hang happens - if there is anything wrong with the BTrace code we should able to spot it from the stack traces (thread dump).

**Comment by Proofkyko** [comment]
I created a rule on the firewall to open that port and checked logs. I cant find the problem. The situation mantains, Btrace will hang at checking port availability without root profile or the connection will be refused when called without administrator privileges.
 
Any other idea ?
 
Francisco Antunes

 
Date: Sat, 25 Jul 2015 13:15:57 -0700

**Comment by jbachorik** [comment]
Ok, try running `btrace --version` to check the version.

Also, try taking thread dump from the traced application when it hangs. It
might reveal some information about what is happening there.

-JB-

**Comment by Proofkyko** [comment]
Version is 1.3.1. It hangs always at the same place, 
DEBUG: checking port availability: 2020.
 
I am running out of ideas and Btrace still does not run
 
Francisco

Date: Wed, 29 Jul 2015 07:37:33 -0700

**Comment by jbachorik** [comment]
Would you try to take thread dump?

It is really difficult to diagnose the issue especially if I am not able to
reproduce it.

-JB-

**Comment by Proofkyko** [comment]
Ok I am looking to thread dump and I am nem to this. What am I looking for ?



No dia 29/07/2015, às 16:07, Jaroslav Bachorik <notifications@github.com> escreveu:

> Would you try to take thread dump?
> 
> It is really difficult to diagnose the issue especially if I am not able to
> reproduce it.
> 
> -JB-
>

**Comment by jbachorik** [comment]
You can use either VisualVM ('jvisualvm' command from the JDK installation)
where you can 'open' the application and create the thread dump. You can
then copy-paste the thread dump here.

Other possibility is to use 'jstack' (command line utility) on the
application and capture the output (either redirect it to a file or
copy-paste from the terminal)

-JB-

**Comment by Proofkyko** [comment]
Some updates here, I was running eclipse under another user, running both eclipse and btrace under the same user it finishes as connection refused. The debug messages are the following :
 
DEBUG: btrace debug mode is set
DEBUG: assuming default port 2020
DEBUG: assuming default classpath '.'
DEBUG: compiling AllCalls1.java
DEBUG: compiled AllCalls1.java
DEBUG: attaching to 1040
DEBUG: checking port availability: 2020
DEBUG: attached to 1040
DEBUG: loading C:\Software\btrace-master\build\btrace-agent.jar
DEBUG: agent args: port=2020,debug=true,systemClassPath=C:\Program Files\Java\jre7/../lib/tools.jar,probeDescPath=.
DEBUG: loaded C:\Software\btrace-master\build\btrace-agent.jar
DEBUG: registering shutdown hook
DEBUG: registering signal handler for SIGINT
DEBUG: submitting the BTrace program
DEBUG: opening socket to 2020
Connection refused: connect
 
Still wanthe thread dump ? Is it from the eclipse program pid or the btrace the one we are interested in ?
 
Francisco

Date: Wed, 29 Jul 2015 08:20:37 -0700

**Comment by jbachorik** [comment]
This would really indicate problems with firewall - https://kenai.com/projects/btrace/forums/forum/topics/542685-Connection-refused-connect

In BTrace a plain socket connect is executed - there is no reason for 'connection refused'.

What if you temporarily turn off the firewall?

**Comment by jbachorik** [comment]
Long time no response. Closing.
