### ISSUE TITLE
how to run the btrace from command prompt

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#148]
I am trying to run the btrace from the command prompt but it is asking me to set the JAVA_HOME before running the file. But i have already mentioned the path of java in environment variables. please tell me how to set and run btrace from command prompt.

**Comment by jbachorik** [comment]
What do you see when you do `echo $JAVA_HOME` ?

**Comment by AbhishekPuligundla** [comment]
thanks i got it, the path really is wrong
