### ISSUE TITLE
tracing a *.jar files from command prompt

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#150]
Hi, i am running the tracing from the command prompt using btracec and btracer. I would like to know if there is a way to run the .jar file using btrace tool from command prompt. The syntax of the btracer shows that it would require the .class file of the mainclass program.

**Comment by jbachorik** [comment]
You can use *btracer* to run a jar with main class, too.
See btracer guide <https://github.com/jbachorik/btrace/wiki/btracer> for
details.

**Comment by AbhishekPuligundla** [comment]
Thank you.
