### ISSUE TITLE
how to trace a war files which are used in tomcat

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#156]
i created a servlet program and added to tomcat server. now I want to trace the java program that is running on the on the tomcat. is it not possible to trace a program that is running on the server. if possible how to specify the name of the class in "clazz" of the OnMethod.

**Comment by jbachorik** [comment]
I really don't get what you are trying to achieve.
But if you want to trace your web application you can use this `@OnMethod(clazz="your.app.package", method="/.*/")` to get info about all the method calls from a particular package.

**Comment by AbhishekPuligundla** [comment]
i want to trace the application which is added to the tomcat server. how can I trace the application that is tomcat server

**Comment by jbachorik** [comment]
As any other application. You can either modify the tomcat server startup scripts to include btrace agent or attach dynamically. There is no special way how to use btrace for tomcat.

**Comment by Tapan2609** [comment]
Hi @jbachorik 

In order to attach btrace to my application deployed in tomcat, I will do it like this "btrace <PID_OF_TOMCAT> TraceScript having @OnMethod(clazz="my.app.package", method="/.*/")". But even though I am hitting my application methods. I am only seeing the trace of Tomcat's internal classes and methods but not my application's. Can you let me know wha

**Comment by Tapan2609** [comment]
@jbachorik I am having a tracescript with @OncrMethod(clazz="my.app.package", method="/.*/") and also my app deployed as a war file in tomcat server. Now, I am attaching "btrace <PID_OF_TOMCAT> tracescript" this way. I am seeing only Tomcat's internal classes and methods being traced but not my application's. Could you please help me here.
