### ISSUE TITLE
starting the application with btrace

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#157]
Is it possible to start the application with btrace which doesn't contain the *.jar file or process ID or *.class file. Is there a way to start the application with btrace using *.bat files.

**Comment by jbachorik** [comment]
Please, see the [BTrace Wiki](https://github.com/jbachorik/btrace/wiki#running-btrace-in-detail) for the details.

**Comment by AbhishekPuligundla** [comment]
What I want was, is it possible to trace an application which doesn't have a .exe file or a .jar file or a .class file. For example take tomcat, how can i start the tomcat with btracer which have a startup file to start the tomcat.

**Comment by AbhishekPuligundla** [comment]
if I use the command btrace in command prompt like "btrace 1345 tracefile.class". Where can I find the tracing output. I didn't find any on the command prompt.

**Comment by jbachorik** [comment]
You can not use the precompiled traces (*.class) when dynamically attaching
BTrace (using the `btrace <PID> ...` command). You must use the source
version (*.java)

**Comment by jbachorik** [comment]
Please, see [this issue](https://github.com/jbachorik/btrace/issues/164) about the problem of submitting precompiled traces.
