### ISSUE TITLE
port 2020 unavailable

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#158]
I tried to trace the tomcat by using the "btrace pid tracefile.java", but it generated message like port 2020 unavailable". If I try to trace the same with the visualVM then it's working. What might be wrong here.

**Comment by jbachorik** [comment]
First, try running `btrace -p <port number> <pid> <tracefile>` with an available port.
If it still does not work, try running btrace in verbose mode - `btrace -v ...` and post the logs here.

**Comment by jbachorik** [comment]
Long time no response. Closing.
If you can reproduce the problem even with a custom port, please, reopen.

**Comment by zhonghuasheng** [comment]
yes, it works for me to use `btrace pid -p port /path/xxx.java`
ie:
`btrace 12345 -p 2021 TestForBTrace.java`
