### ISSUE TITLE
java.lang.VerifyError: Bad return type

### ISSUE THREAD

**Issue by mfilser** [jbachorik/btrace#160]
Hello @jbachorik,
i have on my project an error if i use btrace for performance measure.
I reproduced it, checkout:
https://github.com/mfilser/btraceVerifyError

If you are on linux run the shell script ./test.
Here is the error output:

```
Exception in thread "main" java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    btrace/test/verifyError/Persons.getPerson(Ljava/lang/String;)Lbtrace/test/verifyError/Person; @56: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'btrace/test/verifyError/Person' (from method signature)
  Current Frame:
    bci: @56
    flags: { }
    locals: { 'btrace/test/verifyError/Persons', 'java/lang/String', long, long_2nd, long, long_2nd, 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 1400 1041 b800 1737 0412 21b8 000f bb00
    0000010: 2359 2bb7 0025 3a06 2bb6 002b 9a00 0dbb
    0000020: 002d 592b b700 2e3a 0619 06b8 0017 1604
    0000030: 6541 1221 20b8 001b b0                 
  Stackmap Table:
    append_frame(@41,Long,Long,Object[#4])

        at btrace.test.verifyError.Main.<init>(Main.java:9)
        at btrace.test.verifyError.Main.main(Main.java:14)

**Comment by jbachorik** [comment]
This one is pretty weird. The value on stack was created by directly instantiating either PersonA or PersonB. Regardless, the verifier thinks its type is __java.lang.Object__

I will need more time to analyze this failure.

Thanks for reporting!

**Comment by jbachorik** [comment]
I seem to have found it.

ASM is using 'common superclass' when calculating stack frame maps. In this case it needs to get the common superclass of 'PersonA' and 'PersonB' at a moment when neither of those has been loaded. This leads to using 'java.lang.Object' as the type in the stackframe map for the local variable holding the return value and this verification error.

Fixing this will be pretty tough - the only option would be detecting this situation, not instrumenting the class at the moment it is being loaded and injecting a custom <clinit> block to trigger instrumentation when the class and all the dependencies have already been loaded.

**Comment by mfilser** [comment]
I am not familiar with ASM, byte code manipulation and so on, so it is unfortunately not possible for me to find the bug and to fix it.
Maybe you know a way how to fix it? Or is it a bug of ASM?

**Comment by jbachorik** [comment]
It is a shortcoming of the stack frame map generation algorithm. It is working fine for javac when you have all the classes available. For the runtime bytecode manipulation it is pretty unwieldy :(

Fix will be pretty complicated, if at all possible. I will need some time to ponder different approaches.

**Comment by mfilser** [comment]
Thanks for this information. Take the time you need for the bug fix and i hope that there is a solution for it.
Good luck.

**Comment by mfilser** [comment]
Hello @jbachorik,
sorry for the late answer, i was on vacation.

I tried the commit 894a564  and this commit works as expected. Thanks for your good work ;)
