### ISSUE TITLE
Doubt on @OnError Method Annotation

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#162]
I tried to implement the @OnError by using a simple exception generating code in the @OnMethod, but is not being implemented. I used the following code OnMethod and OnError

@OnMethod(clazz="classname", method="methodname")
public static void method(@ProbeClassName String obj)
{
           i=1/0;         //Arithmetic Exception 
           println(obj);
}
@OnError
public static void method2()
{
          println("exception generated");
}

The above code is simply printing a default Arithmetic Exception Message but not the one i am trying to print in the OnError method. I want to know where some example situations where BTrace generates exceptions and also if there is any mistake in the above code what is right way to do it.

**Comment by jbachorik** [comment]
`@OnError` annotated handler must be a public static method with the following signature: `void (java.lang.Throwable t)`

The example you provided is not compilable in BTrace and __btracec__ should report error.
