### ISSUE TITLE
How to trace from client system

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#163]
I am trying to trace a program from client side. That is the btrace program will be in one system and the application will on another system. how can i trace the application in another system from the system which contains the btrace program. do i have to install the btrace also in the client system or do i have to install the agent in the client system or there is any other way to do it with out any installation at the client system.

**Comment by jbachorik** [comment]
No, currently there is no support for remote tracing in the command line client.

If you think it is interesting feature, please, file an appropriate feature request with detailed description.
