### ISSUE TITLE
unable to open socket file: target process not responding or hotspot vm not loaded

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#166]
I am having the same issue similar to the issue #139. I am using the jdk 7 in redhat linux. it is only happening when i am trying to trace one application. But with other applications its generating connection refused.

**Comment by jbachorik** [comment]
#139 is about trying to use BTrace 1.3.* on JDK 6.

You are saying that you are using JDK 7 on both the server and the client, aren't you?

**Comment by AbhishekPuligundla** [comment]
yes but i am still getting the same message.

**Comment by jbachorik** [comment]
Ok, can you actually *verify* that you are using JDK 7 for the traced application? Eg. run VisualVM and check the JVM details.

**Comment by AbhishekPuligundla** [comment]
Yes, i installed the java 7 in the system. like i said in #169 the application is using another jre 7 which is different from the system. But both the system java and application java are of same version.

**Comment by uninxc** [comment]
check  programe user  is the same
