### ISSUE TITLE
connection refused or well-known file is not secure

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#167]
i am trying to trace the process located in one user of the system with another user of the sytem(say root) which initiates btrace. I am getting an error message like "connection refused". I am running the btrace in redhat linux with java 1.8 . if i change the permission of the root which contains the btrace and trace program then i am getting an message like "well-known file is not secure". I found while googling that by disabling the monitoring feature in glassfish we can avoid similar kind of error. Is there any way do that in linux or is it different problem i am facing.

note: i am getting " connection refused" after chaning the root permissions and also by running the btrace command from the another used. while "well-known file is not secure" is happening while running the btrace command from the root.

**Comment by jbachorik** [comment]
The __Attach API__ used by BTrace is pretty sensitive to access rights. See [these search results](https://www.google.com/search?q=java+well-known+file+is+not+secure&oq=java+well-known+file+is+not+secure&aqs=chrome..69i57j0j69i64l3.1039j0j1&sourceid=chrome&es_sm=122&ie=UTF-8) mentioning thid problem.
