### ISSUE TITLE
Location(kind = Kind.NEWARRAY) should support flexible "clazz" definition

### ISSUE THREAD

**Issue by themoriarty** [jbachorik/btrace#173]
I'm looking into possibility of using btrace as allocation profiler, and it seems very promising.
One of the issues I can't wrap my head around is array allocation tracking. Since "clazz" parameter for NEWARRAY has to be present, and it has to match the type of an array exactly, it's not possible to capture all the array allocations, regardless of their types.
There are at least 2 ways out of it:
 * make "clazz" for NEWARRAY optional and let the user-defined callback handle different types. It would mean certain performance penalty, but only for the cases when "clazz" is absent, so I guess it's not as bad as it sounds.
 * allow "clazz" for NEWARRAY be a regular expression. This might be a little bit involved, since not all parts of btrace code might be prepared for this.

**Comment by jbachorik** [comment]
"clazz" parameter should allow for regular expressions - it does so for eg. FIELD_GET, FIELD_SET or NEW locations.
