### ISSUE TITLE
Doubt on printFields and values printing

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#175]
i want to know how to print only the variables of a method or the parameters passed to a method in source class when a method entry or return or method call has happened.

i Know we can use printFields to print the variable (name,value) pairs. But it will print all the variables of the class that are used by the class.

for example if use printFields(obj); where obj is the object of a class settingsPage i have written. The settingPage is swing program.
The settingspage contains variables like hours,minutes,seconds,h,m,n, which i declared. 
where hours, minutes, seconds  belongs to JComboBox and h,m,n are the integer values. apart from these other variables like layout, alignmentX,border,flags and so on as shown below are being printed which i didn't declared. I know these are the properties or the swing which are being used inbuilt but how to avoid printing all these and only allow printing the variables i declared.

Also i want to know how to print the parameters that are passed to a method when a method is called or invoked in a class or only the variables which are used in a method.
 
the following is the output of prinFields(obj) i am getting
{hours=javax.swing.JComboBox[,49,5,38x22,layout=com.sun.java.swing.plaf.windows.WindowsComboBoxUI$3,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.basic.BasicBorders$FieldBorder@20b1cbe9,flags=328,maximumSize=,minimumSize=,preferredSize=,isEditable=false,lightWeightPopupEnabled=true,maximumRowCount=8,selectedItemReminder=6], minutes=javax.swing.JComboBox[,141,5,38x22,layout=com.sun.java.swing.plaf.windows.WindowsComboBoxUI$3,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.basic.BasicBorders$FieldBorder@23db6776,flags=328,maximumSize=,minimumSize=,preferredSize=,isEditable=false,lightWeightPopupEnabled=true,maximumRowCount=8,selectedItemReminder=8], seconds=javax.swing.JComboBox[,235,5,38x22,layout=com.sun.java.swing.plaf.windows.WindowsComboBoxUI$3,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.basic.BasicBorders$FieldBorder@7fb72d3a,flags=328,maximumSize=,minimumSize=,preferredSize=,isEditable=false,lightWeightPopupEnabled=true,maximumRowCount=8,selectedItemReminder=9], hour=javax.swing.JLabel[,10,9,34x14,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=hours :,verticalAlignment=CENTER,verticalTextPosition=CENTER], minute=javax.swing.JLabel[,92,9,44x14,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=minutes :,verticalAlignment=CENTER,verticalTextPosition=CENTER], second=javax.swing.JLabel[,184,9,46x14,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=seconds :,verticalAlignment=CENTER,verticalTextPosition=CENTER], h=0, m=0, s=0, defaultCloseOperation=1, transferHandler=null, rootPane=javax.swing.JRootPane[,0,0,0x0,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=], rootPaneCheckingEnabled=true, accessibleContext=null, maximizedBounds=null, title=, menuBar=null, resizable=true, undecorated=false, mbManagement=false, state=0, ownedWindows=null, frameSerializedDataVersion=1, warningString=null, icons=null, temporaryLostComponent=null, syncLWRequests=false, beforeFirstShow=true, disposing=false, disposerRecord=java.awt.Window$WindowDisposerRecord@282a21e9, state=0, alwaysOnTop=false, ownedWindowList=[], weakThis=java.lang.ref.WeakReference@4641da17, showWithParent=false, modalBlocker=null, modalExclusionType=NO_EXCLUDE, windowListener=null, windowStateListener=null, windowFocusListener=null, inputContext=null, inputContextLock=java.lang.Object@3262d40c, focusMgr=null, focusableWindowState=true, autoRequestFocus=true, isInShow=false, opacity=1.0, shape=null, isTrayIconWindow=false, securityWarningWidth=0, securityWarningHeight=0, securityWarningPointX=2.0, securityWarningPointY=0.0, securityWarningAlignmentX=1.0, securityWarningAlignmentY=0.0, anchor=java.lang.Object@bb4e66d, type=NORMAL, windowSerializedDataVersion=2, locationByPlatform=false, component=[javax.swing.JRootPane[,0,0,0x0,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=]], layoutMgr=java.awt.BorderLayout[hgap=0,vgap=0], dispatcher=null, focusTraversalPolicy=javax.swing.LayoutFocusTraversalPolicy@28ba21f3, focusCycleRoot=false, focusTraversalPolicyProvider=false, printingThreads=null, printing=false, containerListener=null, listeningChildren=0, listeningBoundsChildren=0, descendantsCount=4, preserveBackgroundColor=null, numOfHWComponents=0, numOfLWComponents=0, modalComp=null, modalAppContext=null, containerSerializedDataVersion=1, peer=null, parent=null, appContext=sun.awt.AppContext[threadGroup=system], x=0, y=0, width=0, height=0, foreground=null, background=javax.swing.plaf.ColorUIResource[r=240,g=240,b=240], font=null, peerFont=null, cursor=java.awt.Cursor[Default Cursor], locale=en_US, graphicsConfig=D3DGraphicsConfig[dev=D3DGraphicsDevice[screen=0],pixfmt=0], bufferStrategy=null, ignoreRepaint=false, visible=false, enabled=true, valid=false, dropTarget=null, popups=null, name=null, nameExplicitlySet=false, focusable=true, isFocusTraversableOverridden=0, focusTraversalKeys=null, focusTraversalKeysEnabled=true, acc=java.security.AccessControlContext@7530d0a, minSize=null, minSizeSet=false, prefSize=null, prefSizeSet=false, maxSize=null, maxSizeSet=false, componentOrientation=java.awt.ComponentOrientation@f2a0b8e, newEventsOnly=true, componentListener=null, focusListener=null, hierarchyListener=null, hierarchyBoundsListener=null, keyListener=null, mouseListener=null, mouseMotionListener=null, mouseWheelListener=null, inputMethodListener=null, windowClosingException=null, eventMask=4168, changeSupport=null, objectLock=java.lang.Object@72e8bb9b, isPacked=false, boundsOp=3, compoundShape=null, mixingCutoutRegion=null, isAddNotifyComplete=false, backgroundEraseDisabled=false, eventCache=null, coalescingEnabled=false, autoFocusTransferOnDisposal=true, componentSerializedDataVersion=4, accessibleContext=null, }

**Comment by jbachorik** [comment]
`BTraceUtils.printFields(obj)` will print all the declared fields of the instance regardless of their visibility or the declaring class. You can prefix the fields with the declaring class name by calling `BTraceUtils.printFields(obj, true)`.

As for the second part of your question - if you want to print all the passed arguments you need to use `AnyType[] args` in the probe handler.
```
@OnMethod(...)
public static void handler(AnyType[] args) {
    BTraceUtils.println("method arguments:");
    BTraceUtils.printArray(args);
}
```
