### ISSUE TITLE
Allow AnyType for arguments annotated by @Return

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#176]
I checked the fixes done at #174. It seems like you have restricted one to use multiple annotations of same type in the same method.

Can i request you for a change as i required to write a single method which will trace two or more methods of a class and prints the return values from different methods of the same or different class.

for example consider the following example source code

public class Classname
{
        public static void main(String args[])
        {
               Classname object1=new Classname();
               int n=object1.method1("hello");
               String s=object1.method2("world");
               boolean r=object1.method3(7);
        }
        int method1(String data)
        {
               int m=7;
              if(data.equals("hello"))
                     return m;
              else
                    return 0;
        }
        String method2(String data1)
        {
                if(data1.equals("hello1"))
                         return data1;
                else
                         return data1;
        }
       boolean method3(int data2)
       {
                if(data2==7)
                           return true;
                else
                            return false;
       }
}

so after the fix in #174 i have to write the @OnMethod for Kind.RETURN like below

@OnMethod(clazz="Classname",method="method1", location=@Location(Kind.RETURN))
public static void tracemethod1(@Return int data)
{
           println(str(data));
}

@OnMethod(clazz="Classname",method="method2", location=@Location(Kind.RETURN))
public static void tracemethod2(@Return int data2)
{
           println(str(data2));
}

@OnMethod(clazz="Classname",method="method3", location=@Location(Kind.RETURN))
public static void tracemethod3(@Return int data3)
{
           println(str(data3));
}

this will increase the number of lines of code i have to write and also one must know what type of return type is used which will be difficult for already running applications.

what i want to try was like below 

@OnMethod(clazz="Classname",method="/.*/",location=@Location(Kind.RETURN))
public static void tracemethod(@Return  DATATYPE data)
{
      println(str(data));
}

I didn't mentioned the datatype in the above method as if i specify datatype that means all the methods are using the same return type. even if i specify a datatype, it will generate an error like invalid return parameter expected character('V' or 'I' or .........). 

What i want to know was is there a way to specify one method to check all the methods like the above single @OnMethod such that the @Return argument must be able to differentiate between the return type returned by different methods.(i.e one will return int ,other one will return char, another one will return boolean and so on ).

**Comment by jbachorik** [comment]
Multiple `@Return` annotations do not make sense. You will always have at most one return value from a method.
You can use `@Return AnyType ret` in order to match any type. Unfortunately, this will not match primitive types right now. I will have to investigate whether `AnyType` can be extended to match primitive types too.
