### ISSUE TITLE
Enhancement: Allow specifying of tools.jar directory

### ISSUE THREAD

**Issue by bvanders** [jbachorik/btrace#182]
As discussed in issue #169, it would be ideal to allow specifying the directory for btrace to find the tools.jar.  btrace currently only looks in the jre/lib directory.  In some cases, that jar may be present in the $JAVA_HOME/lib directory and copying the file to the jre/lib is not desirable.

**Comment by jbachorik** [comment]
BTrace will try and detect __tools.jar__ also in _../lib/tools.jar_. This should help if you are trying to trace an application running on a JRE. Of course this is based on the expectation that the appropriate JDK is installed in the parent folder of the used JRE.

Linking a foreing __tools.jar__ might cause unexpected problems. Is it really needed?

**Comment by bvanders** [comment]
I don't wish to link a foreign tools.jar.  Btrace doesn't appear to look for the jar at ../lib/tools.jar in the version I am using: **BTrace v.1.3 (20150516).**

Java version:
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)

The JVM that I am trying to btrace is a tomcat process with its JAVA_HOME pointing to the *jre* directory.  Attempts to run a btrace script against this result in 

````
...
DEBUG: server not yet available; retrying ...
DEBUG: server not yet available; retrying ...
DEBUG: server not yet available; retrying ...
Exception in thread "main" java.lang.NullPointerException
	at com.sun.btrace.client.Client.submit(Client.java:353)
	at com.sun.btrace.client.Main.main(Main.java:189)
DEBUG: sending exit command
Exception in thread "Thread-0" java.lang.IllegalStateException
	at com.sun.btrace.client.Client.send(Client.java:458)
	at com.sun.btrace.client.Client.sendExit(Client.java:392)
	at com.sun.btrace.client.Main$2.run(Main.java:226)
	at java.lang.Thread.run(Thread.java:745)
````

However, when I copy the tools.jar to the *jre/lib/* directory, btrace executes as expected.

**Comment by jbachorik** [comment]
Hm, let me check. The code to look for ../lib/tools.jar is definitely [there](https://github.com/jbachorik/btrace/blob/master/src/share/classes/com/sun/btrace/client/Client.java#L471). It might be that JAVA_HOME contains a wrong value when BTrace client is processing it.

**Comment by jbachorik** [comment]
What is the operating system?

This works pretty well locally on my Linux machine.

**Comment by bvanders** [comment]
It's Linux.  Ubuntu.  

I'll try building the latest btrace and experimenting with directory permissions to see if I can provide more details about the problem.

**Comment by jbachorik** [comment]
@bvanders Any progress on this?

**Comment by jbachorik** [comment]
@bvanders Any progress on this?

**Comment by bvanders** [comment]
I haven't touched it recently.  My recollection is that the binary I downloaded was "broken."  However, when I built btrace from the source code available, it seemed to not suffer the same problem. That was several months ago.  I'll close this and reopen if I have more info to add.
