### ISSUE TITLE
how to install btrace as a plugin in visualvm?

### ISSUE THREAD

**Issue by Boli-CS** [jbachorik/btrace#191]
hi, i'm new to use visualvm and brace and i am facing a easy problem but i have not idea.

i installed visualvm 1.3.8 in my mac and try to install btrace workbench as a plugin. but is says: the plugin org.openide.util.ui is requested in version 9.4.1. i search by google but failed to get the plugin named openide.

**Comment by jbachorik** [comment]
There was a problem with dependencies. It is fixed now on VisualVM update center.
