### ISSUE TITLE
Needs for tracing return event for 'void' methods only

### ISSUE THREAD

**Issue by yburkouski** [jbachorik/btrace#192]
With a 'location = @Location(Kind.RETURN)' and '@Return AnyType ret' I can trigger and get return from any methods except of constructors (<init>) and with 'void' return signature.
I suggest to use for this case a variant with '@Return java.lang.Void ret' cause there is only 1 alternate: using '@Location(Kind.RETURN)' without '@Return' (it catches return method event for constructors and 'void' methods), but in this case it's impossible to get method return value. AnyType is not suitable for catching it because it would be impossible to tell 'void' from 'null' return.
I'm using this app for testing: https://github.com/yburkouski/Btrace-Test-App

**Comment by jbachorik** [comment]
Could you clarify the request? Do you want to trace only 'void' returns or all returns, including 'void'?

**Comment by yburkouski** [comment]
**only void** methods: methods that has been declared like `void m(){...}` + constructors

cause right now there is possible to trace all methods including 'void' (without Return annotation), and any non void methods (with Return annotation), but there is impossible to trace only void return methods.

**Comment by jbachorik** [comment]
There is a proposed solution in https://github.com/jbachorik/btrace/tree/anytype-void-return branch.

In order to trace only void returning methods you will need to declare the `@Return` parameter to be of `java.lang.Void` type - 
```
@OnMethod(clazz = "cls", method = "mthd", location = @Location(Kind.RETURN))
public static void dotrace(@Return Void dummy) {
...
}
```

Please, verify if this resolves your problems.

**Comment by jbachorik** [comment]
@yburkouski Are you fine with the proposed solution?

**Comment by yburkouski** [comment]
@jbachorik sorry for delay, I will test it tomorrow.

**Comment by yburkouski** [comment]
@jbachorik works as expected. Thanks!
