### ISSUE TITLE
Unable to create aggregations

### ISSUE THREAD

**Issue by maxmil** [jbachorik/btrace#193]
I have just started using BTrace. It's great, thanks. It runs fine and I've used a bunch of its API's however I've run into a problem trying out aggregations.

`Aggregations.newAggregation(AggregationFunction.AVERAGE)`

results in

`java.lang.NoSuchFieldError: $AVERAGE`

I'm using 1.3.4. Is this a bug or is it just me?

**Comment by jbachorik** [comment]
Please, make sure that you are really running version 1.3.4 - the output of `btrace --version` should be 'BTrace v.1.3.4 (20151107)'

I am not able to reproduce on a freshly downloaded 1.3.4 release.

If you can reproduce the problem, run btrace with __-d <path>__ parameter to dump the probe class and instrumented classes to <path> and attach the dumped classes here.

**Comment by jbachorik** [comment]
Closing because of no response.
Feel free to reopen with more information.
