### ISSUE TITLE
Every TestCase occurs this error:java.lang.IllegalArgumentException! Crazy!

### ISSUE THREAD

**Issue by hanzhankang** [jbachorik/btrace#194]
java.lang.IllegalArgumentException
	at com.sun.btrace.org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at com.sun.btrace.agent.Client$3.<init>(Client.java:423)
	at com.sun.btrace.agent.Client.verify(Client.java:423)
	at com.sun.btrace.agent.Client.loadClass(Client.java:238)
	at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:59)
	at com.sun.btrace.agent.Main.startServer(Main.java:416)
	at com.sun.btrace.agent.Main.access$000(Main.java:66)
	at com.sun.btrace.agent.Main$2.run(Main.java:171)
	at java.lang.Thread.run(Thread.java:745)
DEBUG: received com.sun.btrace.comm.ExitCommand@1877ab81

When I run simple test , such as :

`@BTrace public class TracingScript {

    @OnTimer(4000)
    public static void printMem() {
        println("Heap:");
        println(Sys.Memory.heapUsage());
        println("Non-Heap:");
        println(Sys.Memory.nonHeapUsage());
    }
}`

I use debug with command :
`btrace -v -d ./dumpfiles 3920 /Users/xxx/Test/src/main/java/btrace/TracingScript.java`
(I alread set environment path for java & btrace !)

the result :
`$ btrace -v -d ./dumpfiles 3920  /Users/xxx/Test/src/main/java/btrace/TracingScript.java
DEBUG: dumpDir is ./dumpfiles
DEBUG: assuming default port 2020
DEBUG: assuming default classpath '.'
DEBUG: compiling /Users/xxx/Test/src/main/java/btrace/TracingScript.java
DEBUG: compiled /Users/xxx/Test/src/main/java/btrace/TracingScript.java
DEBUG: attaching to 3920
DEBUG: checking port availability: 2020
DEBUG: attached to 3920
DEBUG: loading /Users/xxx/opensource/btrace-1.3/build/btrace-agent.jar
DEBUG: agent args: port=2020,statsd=,debug=true,dumpClasses=true,dumpDir=./dumpfiles,systemClassPath=/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/lib/tools.jar,probeDescPath=.
DEBUG: loaded /Users/xxx/opensource/btrace-1.3/build/btrace-agent.jar
DEBUG: registering shutdown hook
DEBUG: registering signal handler for SIGINT
DEBUG: submitting the BTrace program
DEBUG: opening socket to 2020
DEBUG: sending instrument command
DEBUG: entering into command loop
DEBUG: received com.sun.btrace.comm.ErrorCommand@57e1b0c
java.lang.IllegalArgumentException
	at com.sun.btrace.org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at com.sun.btrace.agent.Client$3.<init>(Client.java:423)
	at com.sun.btrace.agent.Client.verify(Client.java:423)
	at com.sun.btrace.agent.Client.loadClass(Client.java:238)
	at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:59)
	at com.sun.btrace.agent.Main.startServer(Main.java:416)
	at com.sun.btrace.agent.Main.access$000(Main.java:66)
	at com.sun.btrace.agent.Main$2.run(Main.java:171)
	at java.lang.Thread.run(Thread.java:745)
DEBUG: received com.sun.btrace.comm.ExitCommand@1877ab81`

I am a freshman for Btrace. It is my first try.And it costed about total night. Crazy!

Can you tell me what's the reason ? Unluck?!

**Comment by hanzhankang** [comment]
$ ./gradlew build
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:assemble
:unjar UP-TO-DATE
:agentJar UP-TO-DATE
:bootJar UP-TO-DATE
:buildDTrace SKIPPED
:clientJar UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:buildTraces UP-TO-DATE
:test

com.sun.btrace.BTraceFunctionalTests > testOSMBean FAILED
    java.lang.AssertionError at BTraceFunctionalTests.java:58

com.sun.btrace.BTraceFunctionalTests > testOnProbe FAILED
    java.lang.AssertionError at BTraceFunctionalTests.java:73

com.sun.btrace.BTraceFunctionalTests > testOnMethod FAILED
    java.lang.AssertionError at BTraceFunctionalTests.java:90

98 tests completed, 3 failed
:test FAILED

FAILURE: Build failed with an exception.

**Comment by hanzhankang** [comment]
$ ./gradlew buildDistributions
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:unjar UP-TO-DATE
:agentJar UP-TO-DATE
:bootJar UP-TO-DATE
:clientJar UP-TO-DATE
:buildDeb
Building data
file:./usr/lib/btrace/btrace-agent.jar size:374458 mode:420 ....
Building control
:buildRpm
:buildDTrace SKIPPED
:createBinDistTgz
:createBinDistZip
:buildDistributions

BUILD SUCCESSFUL

Total time: 4.889 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html

**Comment by hanzhankang** [comment]
$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

btrace-1.3

**Comment by jbachorik** [comment]
This is really weird.
Please, checkout the 'btrace' repository afresh and switch to 'realease-1.3' branch. After that do 
`./gradlew clean build`

**Comment by jbachorik** [comment]
Build log from a fresh clone - [btrace_build.txt](https://github.com/jbachorik/btrace/files/112278/btrace_build.txt)

**Comment by hanzhankang** [comment]
./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'btrace'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2.
     Required by:
         :btrace:unspecified
      > Could not resolve com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2.
         > Could not get resource 'https://plugins.gradle.org/m2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.2/gradle-bintray-plugin-1.2.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.2/gradle-bintray-plugin-1.2.pom'.
               > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.253 secs

-------Maybe our network is broken. I am come from China...

**Comment by jbachorik** [comment]
If you try following the links in your browser, do they work?
Also, did you clone BTrace to a new destination?

**Comment by tmohme** [comment]
The last line ("peer not authenticated") of the posted error messages points to an ssl problem.
Running with "--stacktrace" could give detail infos to verify/falsify this hypothesis.
You should try to follow Alex Lipov's answer in [this thread](http://stackoverflow.com/questions/26734738/android-studio-gradle-build-failed-errorcause-peer-not-authenticated) or VD's answer in [this thread](http://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse).

**Comment by jbachorik** [comment]
Closing. If you reproduce this with a fresh BTrace clone, please, reopen with all the logs.
