### ISSUE TITLE
NoClassDefFoundError in target application

### ISSUE THREAD

**Issue by gwi2014** [jbachorik/btrace#196]
Hello,
I'm trying to connect to a Jira installation running on Tomcat 7.0.55 with JDK 1.8.0_51. Depending on what I'm trying to trace I run into this exception in Jira:

`Caused by: java.lang.ClassNotFoundException: com.sun.btrace.BTraceRuntime
	at org.apache.felix.framework.ModuleImpl.findClassOrResourceByDelegation(ModuleImpl.java:772)
	at org.apache.felix.framework.ModuleImpl.access$200(ModuleImpl.java:73)
	at org.apache.felix.framework.ModuleImpl$ModuleClassLoader.loadClass(ModuleImpl.java:1690)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
`

Once this exceptions occurs, the tomcat fails to shutdown.

It seems that this is problem with multiple classloaders. Should this work? Do you have any advice on how to work around this?

Thanks,
Guido

**Comment by jbachorik** [comment]
It is an OSGI issue. Please, refer to this [thread](https://kenai.com/projects/btrace/forums/tips-tricks/topics/7221-BTrace-with-OSGI).

**Comment by gwi2014** [comment]
Thank you very much, that helped. If anybody runs into this, you have to start your application server with:

`-Dorg.osgi.framework.bootdelegation=com.sun.btrace,com.sun.btrace.*`

Thanks,
Guido
